version: "3.9"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=hello-db

  grpc:
    build:
      context: ./src/grpc-dotnet
    ports:
      - 5000:5000
    depends_on:
      - db